### ISSUE TITLE
The context menu of the icons on the panel displays away

### ISSUE THREAD

**Issue by haggen88** [linuxmint/wayland#21]
### Distribution

Mint 21.3

### Package version

cinnamon 6.0.4

### Frequency

Always

### Bug description

When right-clicking on the tray icons, the menus are displayed too far apart.

- sticky
![w-menu a la cresta](https://github.com/linuxmint/wayland/assets/68134588/63967f00-3988-4657-91d1-e1283e1057cb)

terminal output when right clicking on tray icon:
mint@mint:~$ sticky

(sticky.py:21815): Gdk-WARNING **: 04:05:15.951: Couldn't map as window 0x55f68076ab80 as popup because it doesn't have a parent

- mintupdate
![w-desalineado icon tray ](https://github.com/linuxmint/wayland/assets/68134588/b2fb3a18-6112-42a6-bccf-e0eca5d3de3f)

![w-clic derecho muestra menu my lejos de mintupdate](https://github.com/linuxmint/wayland/assets/68134588/0846f015-451e-4902-8d59-c2fd644d647f)

terminal output when right clicking on tray icon:
(mintUpdate.py:22194): Gdk-WARNING **: 04:08:25.966: Couldn't map as window 0x55ffb79f0440 as popup because it doesn't have a parent

### Steps to reproduce

right click on the tray icon

### Expected behavior

that the menu is displayed near the tray icon

**Comment by ENRORMA** [comment]
I have the same Problem on cinnamon 6.0.4
and sometimes when i right click on the tray icon for steam nothing happens

**Comment by TerminusDeus** [comment]
The following workaround worked for me in scope of Linux Mint 21.3 Cinnamon (6.0.4) wayland experimental session (mintupdate 6.1.0):
1. for proper Update manager tray menu position: quit from Update manager and then run GDK_BACKEND=x11 mintupdate-launcher
2. for proper xapp-xn-watcher menus (e.g. steam tray menu, flatpak apps (running under x11 socket) tray menus) position: GDK_BACKEND=x11 /usr/lib/x86_64-linux-gnu/xapps/xapp-sn-watcher

It could be used in Startup applications GUI by creating startup items for launching mintupdate-launcher & xapp-sn-watcher (/etc/xdg/autostart/xapp-sn-watcher.desktop could be modified also) and rebooting.

**Comment by yobenbobin** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/20978824-b146-4e46-a69c-fb1269b06997" />

system:
Linux Mint 22.3 - Cinnamon 64-bit
Cinnamon 6.6.3
Wayland

Same problem.

**Comment by mtwebster** [comment]
Fixed in muffin and libxapp.

https://github.com/linuxmint/xapp/commit/9caa27d216287fe750e69e2da1c5cb7c580e5318
https://github.com/linuxmint/muffin/commit/206c0ae9715fab88f258a04de97136533d3cf89d

**Comment by SeniorMatt** [comment]
> Fixed in muffin and libxapp.
> 
> [linuxmint/xapp@9caa27d](https://github.com/linuxmint/xapp/commit/9caa27d216287fe750e69e2da1c5cb7c580e5318) [linuxmint/muffin@206c0ae](https://github.com/linuxmint/muffin/commit/206c0ae9715fab88f258a04de97136533d3cf89d)

Hey, I know this is probably not the right place to ask, but is there any guide on how I can compile the latest Cinnamon and the dependencies from GitHub?

**Comment by ArqamQazi** [comment]
The issue is not resolved, the menu appears in center now.

<img width="3301" height="1842" alt="Image" src="https://github.com/user-attachments/assets/6e8b514b-df7f-4ddd-85f9-02e2371f8ddd" />

**Comment by leigh123linux** [comment]
Locked to due irrelevant comments, it's fixed in 6.7.1-unstable and probably wont be applied to 6.6.x release ever.
