### ISSUE TITLE
Black lines around UI elements with fractional scaling

### ISSUE THREAD

**Issue by axel358** [linuxmint/wayland#81]
### Distribution

Mint 21.3

### Package version

Muffin 6.X

### Graphics hardware in use

Intel Iris

### Frequency

Always

### Bug description

Black outlined rectangles flicker around UI elements, buttons, windows etc.

Possibly related issues:
https://gitlab.gnome.org/GNOME/mutter/-/issues/1500

https://discourse.gnome.org/t/weird-windows-flickering-borders-on-gnome-3-36-with-fractional-scaling-enabled/3953

Potential fixes:
https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1554

### Steps to reproduce

Enable fractional scaling 

### Expected behavior

No lines

**Comment by ddouglas87** [comment]
Same bug.  Someone else on Reddit wrote about experiencing the same bug too.  I suspect this is the case for all graphics cards or just Nvidia graphics cards.  My system is a vanilla fresh install of Mint 21.3 with only these modifications:

Accessibility: Large Text
Two 4k monitors plugged in, first fractional scaling 150%, second 200%.
Installed Nvidia video driver 555.52.04.
System updates up to date as of Jun 29th, 2024.
Installed nvidia-vaapi-driver, version v0.0.12  (Used for hardware youtube video playback in Firefox.)

Notes about my system:

```
bunny@happy:~$ neofetch
             ...-:::::-...                 bunny@happy 
          .-MMMMMMMMMMMMMMM-.              ----------- 
      .-MMMM`..-:::::::-..`MMMM-.          OS: Linux Mint 21.3 x86_64 
    .:MMMM.:MMMMMMMMMMMMMMM:.MMMM:.        Host: MS-7673 2.0 
   -MMM-M---MMMMMMMMMMMMMMMMMMM.MMM-       Kernel: 5.15.0-113-generic 
 `:MMM:MM`  :MMMM:....::-...-MMMM:MMM:`    Uptime: 2 mins 
 :MMM:MMM`  :MM:`  ``    ``  `:MMM:MMM:    Packages: 2455 (dpkg), 15 (flatpak), 
.MMM.MMMM`  :MM.  -MM.  .MM-  `MMMM.MMM.   Shell: bash 5.1.16 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   Resolution: 3840x2160, 5120x2880 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM:MMM:   DE: Cinnamon 6.0.4 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   WM: Mutter (Muffin) 
.MMM.MMMM`  :MM:--:MM:--:MM:  `MMMM.MMM.   WM Theme: Mint-Y-Dark-Aqua (Mint-Y) 
 :MMM:MMM-  `-MMMMMMMMMMMM-`  -MMM-MMM:    Theme: Mint-Y-Dark-Aqua [GTK2/3] 
  :MMM:MMM:`                `:MMM:MMM:     Icons: Mint-Y-Sand [GTK2/3] 
   .MMM.MMMM:--------------:MMMM.MMM.      Terminal: gnome-terminal 
     '-MMMM.-MMMMMMMMMMMMMMM-.MMMM-'       CPU: Intel i5-2500K (4) @ 3.700GHz 
       '.-MMMM``--:::::--``MMMM-.'         GPU: NVIDIA GeForce GTX 980 
            '-MMMMMMMMMMMMM-'              Memory: 2142MiB / 23980MiB 
               ``-:::::-``
                                                                   
                                                                  
bunny@happy:~$ muffin --version
mutter 6.0.1
Copyright © 2001-2011 Havoc Pennington, Red Hat, Inc., and others
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


bunny@happy:~$ modinfo nvidia
filename:       /lib/modules/5.15.0-113-generic/updates/dkms/nvidia.ko
alias:          char-major-195-*
version:        555.52.04
supported:      external
license:        NVIDIA
firmware:       nvidia/555.52.04/gsp_tu10x.bin
firmware:       nvidia/555.52.04/gsp_ga10x.bin
srcversion:     7CC59AD55E0DD69F0C28592
alias:          pci:v000010DEd*sv*sd*bc06sc80i00*
alias:          pci:v000010DEd*sv*sd*bc03sc02i00*
alias:          pci:v000010DEd*sv*sd*bc03sc00i00*
depends:        drm
retpoline:      Y
name:           nvidia
vermagic:       5.15.0-113-generic SMP mod_unload modversions 
sig_id:         PKCS#7
signer:         localhost.localdomain Secure Boot Module Signature key
sig_key:        02:E9:E7:A2:4A:F9:D1:E5:23:69:9F:CF:7B:BE:7C:41:34:5C:90:AB
sig_hashalgo:   sha512
signature:      3D:26:44:CA:A2:B3:9B:5D:7B:A0:A4:E7:87:52:9E:83:4B:8F:FD:17:
		0D:65:0F:AD:AC:B5:AF:B0:06:47:C6:3F:E8:D0:AE:D0:E2:8C:9C:BF:
		C8:2D:D0:CD:1E:D6:41:53:F5:27:62:54:C0:2A:39:D2:15:87:BA:4D:
		8F:5A:35:F0:51:4C:1E:8B:4B:EA:4F:D3:27:4D:B5:74:E0:2C:7E:BE:
		69:7F:5B:E2:01:7D:D8:51:0D:94:36:62:BC:C7:F3:B1:1D:23:01:C7:
		EA:76:04:E0:63:7D:E7:BE:5E:9F:A6:05:3B:22:EE:9B:E3:38:06:A5:
		01:60:DF:DC:21:78:F1:30:6A:10:1F:F4:FD:C8:EC:32:F6:BE:93:2D:
		B7:07:6A:FB:A4:0F:52:C5:73:0B:18:FA:84:0A:AF:13:A8:78:96:D7:
		44:FE:15:D1:18:25:56:D7:A6:91:25:77:50:05:F5:03:72:7F:96:A1:
		12:67:BD:D9:13:EC:59:FC:BE:6E:90:22:9B:78:4B:B4:36:BC:E9:B4:
		E4:76:44:2F:BD:DD:9D:D2:C8:DC:22:85:80:F6:F1:FD:45:D9:7A:4D:
		B1:10:80:93:59:C6:54:DB:44:0C:98:BF:7E:54:38:F0:C0:22:E6:F5:
		E2:50:D0:EF:3A:DE:18:88:FC:97:50:CB:D1:DC:4C:C1
parm:           NvSwitchRegDwords:NvSwitch regkey (charp)
parm:           NvSwitchBlacklist:NvSwitchBlacklist=uuid[,uuid...] (charp)
parm:           NVreg_ResmanDebugLevel:int
parm:           NVreg_RmLogonRC:int
parm:           NVreg_ModifyDeviceFiles:int
parm:           NVreg_DeviceFileUID:int
parm:           NVreg_DeviceFileGID:int
parm:           NVreg_DeviceFileMode:int
parm:           NVreg_InitializeSystemMemoryAllocations:int
parm:           NVreg_UsePageAttributeTable:int
parm:           NVreg_EnablePCIeGen3:int
parm:           NVreg_EnableMSI:int
parm:           NVreg_TCEBypassMode:int
parm:           NVreg_EnableStreamMemOPs:int
parm:           NVreg_RestrictProfilingToAdminUsers:int
parm:           NVreg_PreserveVideoMemoryAllocations:int
parm:           NVreg_EnableS0ixPowerManagement:int
parm:           NVreg_S0ixPowerManagementVideoMemoryThreshold:int
parm:           NVreg_DynamicPowerManagement:int
parm:           NVreg_DynamicPowerManagementVideoMemoryThreshold:int
parm:           NVreg_EnableGpuFirmware:int
parm:           NVreg_EnableGpuFirmwareLogs:int
parm:           NVreg_OpenRmEnableUnsupportedGpus:int
parm:           NVreg_EnableUserNUMAManagement:int
parm:           NVreg_MemoryPoolSize:int
parm:           NVreg_KMallocHeapMaxSize:int
parm:           NVreg_VMallocHeapMaxSize:int
parm:           NVreg_IgnoreMMIOCheck:int
parm:           NVreg_NvLinkDisable:int
parm:           NVreg_EnablePCIERelaxedOrderingMode:int
parm:           NVreg_RegisterPCIDriver:int
parm:           NVreg_EnableResizableBar:int
parm:           NVreg_EnableDbgBreakpoint:int
parm:           NVreg_EnableNonblockingOpen:int
parm:           NVreg_RegistryDwords:charp
parm:           NVreg_RegistryDwordsPerDevice:charp
parm:           NVreg_RmMsg:charp
parm:           NVreg_GpuBlacklist:charp
parm:           NVreg_TemporaryFilePath:charp
parm:           NVreg_ExcludedGpus:charp
parm:           NVreg_DmaRemapPeerMmio:int
parm:           NVreg_RmNvlinkBandwidth:charp
parm:           NVreg_ImexChannelCount:int
parm:           NVreg_CreateImexChannel0:int
parm:           rm_firmware_active:charp


bunny@happy:~$ cat /etc/environment
# Hardware Accelerated Youtube Video Playback
LIBVA_DRIVER_NAME=nvidia
MOZ_DISABLE_RDD_SANDBOX=1
__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json
#NVD_BACKEND=egl
```

**Comment by Susensio** [comment]
Same problem on Mint 22, integrated intel graphics card.
It's a shame because fractional scaling on X introduces a lot of lag, and same on wayland introduces these black boxes.

**Comment by bramtechs** [comment]
Same issue on AMD RX 5600 XT on 4K monitor with scaling set to 150%.
Running on Debian Trixie.

**Comment by 64BitUniverse** [comment]
Same with Linux Mint 22 and Cinnamon on a Framework 13 AMD 7040 on 150% Scale. Seems that when ever something changes on the screen the lines appear. Is there a way to debug these lines to try and help find a solution?

**Comment by IrishBruse** [comment]
Tried out wayland again recently and it seemed to work alot better with gtx 970 and the 570 drivers and latest version of cinnamon it used to crash very fast for me before
I am getting these black boxes too with a 1440p monitor at 125% scaling

**Comment by gyf9835** [comment]
Encountered the same problem
Linux Mint 22.1
VNIDIA Driver Version: 570.169
RTX3060

![Image](https://github.com/user-attachments/assets/5d5e4fdf-3259-4e6d-be40-bf044cc5bbed)

**Comment by bramtechs** [comment]
It's funny being reminded how Wayland on Linux is still a broken mess a year later. I've completely given up at this point and keep using X11. (I have nothing against Linux Mint specifically, but Wayland just doesn't work.)

**Comment by 64BitUniverse** [comment]
It can work, it's just that no one has really bothered with fully implementing it until super recently

**Comment by axel358** [comment]
> It's funny being reminded how Wayland on Linux is still a broken mess a year later. I've completely given up at this point and keep using X11. (I have nothing against Linux Mint specifically, but Wayland just doesn't work.)

This issue does not exist in upstream mutter, it was fixed about 4 years ago. Mint is using a fork of mutter 3.36 which is 5 years old now, they have stated their reasons for not updating it, but, in short that's the real issue here, outdated unmaintained software, not Wayland

**Comment by Tuxman2** [comment]
Bug is still present in Linux Mint 22.2 beta with Wayland session.

**Comment by Sunderland93** [comment]
Please test this PR https://github.com/linuxmint/muffin/pull/777

**Comment by axel358** [comment]
Using these builds I still get the screen artifacts around windows and UI elements when hovering them with the pointer. I dunno if I might have missed something or if CI didn't use the right branch 

https://github.com/axel358/muffin/releases/tag/fix_region_clipping.mint22

**Comment by Hansonwong47** [comment]
In short, thank you very much for the fix. Although the human test has not yet been successful, I hope you can continue to improve and fix this problem (to resolve the issues that Linux Mint is causing with Wayland).

> Please test this PR [linuxmint/muffin#777](https://github.com/linuxmint/muffin/pull/777)

**Comment by Sunderland93** [comment]
@axel358 @Hansonwong47 please check the latest commits. I tested https://github.com/linuxmint/muffin/pull/777 on Radeon RX 570 with 125% and 175% scaling. Black lines and other glitches no longer exists.

**Comment by Hansonwong47** [comment]
> [@axel358](https://github.com/axel358) [@Hansonwong47](https://github.com/Hansonwong47) please check the latest commits. I tested [linuxmint/muffin#777](https://github.com/linuxmint/muffin/pull/777) on Radeon RX 570 with 125% and 175% scaling. Black lines and other glitches no longer exists.

I want to ask that how to use this version? just install the newest version of linux mint?

**Comment by Sunderland93** [comment]
> I want to ask that how to use this version? just install the newest version of linux mint?

No, just Muffin from "fix_region_clipping" branch https://github.com/Sunderland93/muffin/releases/tag/fix_region_clipping.mint22

**Comment by Hansonwong47** [comment]
> > I want to ask that how to use this version? just install the newest version of linux mint?
> 
> No, just Muffin from "fix_region_clipping" branch https://github.com/Sunderland93/muffin/releases/tag/fix_region_clipping.mint22

So how can i use? i need to download?

**Comment by Sunderland93** [comment]
> So how can i use? i need to download?

Yes, download `packages.tar.gz`, unpack it and install all .deb packages from it via `sudo dpkg -i *.deb` then re-login to session or reboot

**Comment by Hansonwong47** [comment]
> > So how can i use? i need to download?
> 
> Yes, download `packages.tar.gz`, unpack it and install all .deb packages from it via `sudo dpkg -i *.deb` then re-login to session or reboot

So it's not installed by default (this version is pre-installed), you have to install it manually?

**Comment by Hansonwong47** [comment]
> > So how can i use? i need to download?
> 
> Yes, download `packages.tar.gz`, unpack it and install all .deb packages from it via `sudo dpkg -i *.deb` then re-login to session or reboot

Because this version is yours.

**Comment by Sunderland93** [comment]
This patch is not yet merged, so you have to install packages built with it manually

**Comment by Sunderland93** [comment]
It looks like the packages I mentioned above are being built from the wrong branch. So you need to build it manually.

I've also tested https://github.com/linuxmint/muffin/pull/777 on my laptop with Intel HD Graphics 620, and it's also works pretty well, no rendering issues at all.

**Comment by Hansonwong47** [comment]
I don't know why they just not allow to merged but  it just can faster to fix the question and @Sunderland93 help them to fix and no bug!!! I don't know why they just not allow, i hope they just more faster to allow it

**Comment by Hansonwong47** [comment]
> I don't know why they just not allow to merged but it just can faster to fix the question and [@Sunderland93](https://github.com/Sunderland93) help them to fix and no bug!!! I don't know why they just not allow, i hope they just more faster to allow it

I tried to persuade them to merge quickly, but they were perceived as being impolite. There's nothing I can do but wait for the official process to proceed or for the merger to happen sooner.

**Comment by Hansonwong47** [comment]
> It looks like the packages I mentioned above are being built from the wrong branch. So you need to build it manually.
> 
> I've also tested [linuxmint/muffin#777](https://github.com/linuxmint/muffin/pull/777) on my laptop with Intel HD Graphics 620, and it's also works pretty well, no rendering issues at all.

You see that it doesn't have any bug(he test it)

**Comment by axel358** [comment]
Just tested the changes and they're working pretty great! So far I can't spot any glitched or regressions introduced by this change. @Sunderland93 thank you very much for all the work you're putting into making the Wayland experience with cinnamon so much better.

**Comment by Hansonwong47** [comment]
> Just tested the changes and they're working pretty great! So far I can't spot any glitched or regressions introduced by this change. [@Sunderland93](https://github.com/Sunderland93) thank you very much for all the work you're putting into making the Wayland experience with cinnamon so much better.

Thanks @Sunderland93 @axel358  who fix the error and who test it, but now, have a problem is that is I don't know what's wrong with the official team, but they just won't merge the resolved branches into the main branch.

**Comment by Hansonwong47** [comment]
> > Just tested the changes and they're working pretty great! So far I can't spot any glitched or regressions introduced by this change. [@Sunderland93](https://github.com/Sunderland93) thank you very much for all the work you're putting into making the Wayland experience with cinnamon so much better.
> 
> Thanks [@Sunderland93](https://github.com/Sunderland93) [@axel358](https://github.com/axel358) who fix the error and who test it, but now, have a problem is that is I don't know what's wrong with the official team, but they just won't merge the resolved branches into the main branch.

@mtwebster This presents some difficulties for those using Linux Mint Wayland, as it requires manual building and installation. I don't know if the official team decided to fix it themselves instead of merging it with the already resolved mainline because they were afraid you would steal the credit, but if something goes wrong, it should be merged immediately instead of being delayed. I don't mean to criticize you, but your actions have been too slow.

**Comment by Hansonwong47** [comment]
@mtwebster I just want the integration to be completed quickly. Once integrated, we can directly fix the major issues with Wayland (scaling problems). But when I urged you, some people scolded me and told me to watch my tone. I don't know what you're trying to achieve, but manually removing components can be a huge obstacle for Linux beginners. If we can integrate quickly, it will be ready to use immediately without needing to solve any problems.

**Comment by leigh123linux** [comment]
@Hansonwong47 

Use X until it's merged.
Wayland support is still experimental, it's issues don't get priority.

**Comment by leigh123linux** [comment]
> [@mtwebster](https://github.com/mtwebster) I just want the integration to be completed quickly. Once integrated, we can directly fix the major issues with Wayland (scaling problems). But when I urged you, some people scolded me and told me to watch my tone. I don't know what you're trying to achieve, but manually removing components can be a huge obstacle for Linux beginners. If we can integrate quickly, it will be ready to use immediately without needing to solve any problems.

I warned you to stop and you didn't. post locked.
